INSERT INTO public.bookshelves (id, name) VALUES (1, 'United States Law');
INSERT INTO public.bookshelves (id, name) VALUES (2, 'Politics');
INSERT INTO public.bookshelves (id, name) VALUES (3, 'American Revolutionary War');
INSERT INTO public.bookshelves (id, name) VALUES (4, 'US Civil War');
INSERT INTO public.bookshelves (id, name) VALUES (5, 'United States');
INSERT INTO public.bookshelves (id, name) VALUES (6, 'Children''s Literature');
INSERT INTO public.bookshelves (id, name) VALUES (7, 'Best Books Ever Listings');
INSERT INTO public.bookshelves (id, name) VALUES (8, 'CIA World Factbooks');
INSERT INTO public.bookshelves (id, name) VALUES (9, 'Adventure');
INSERT INTO public.bookshelves (id, name) VALUES (10, 'Movie Books');
INSERT INTO public.bookshelves (id, name) VALUES (11, 'Latter Day Saints');
INSERT INTO public.bookshelves (id, name) VALUES (12, 'Christianity');
INSERT INTO public.bookshelves (id, name) VALUES (13, 'Poetry');
INSERT INTO public.bookshelves (id, name) VALUES (14, 'Native America');
INSERT INTO public.bookshelves (id, name) VALUES (15, 'Banned Books from Anne Haight''s list');
INSERT INTO public.bookshelves (id, name) VALUES (16, 'Reference');
INSERT INTO public.bookshelves (id, name) VALUES (17, 'African American Writers');
INSERT INTO public.bookshelves (id, name) VALUES (18, 'Slavery');
INSERT INTO public.bookshelves (id, name) VALUES (19, 'Harvard Classics');
INSERT INTO public.bookshelves (id, name) VALUES (20, 'Plays');
INSERT INTO public.bookshelves (id, name) VALUES (21, 'Science Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (22, 'Horror');
INSERT INTO public.bookshelves (id, name) VALUES (23, 'Precursors of Science Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (24, 'Gothic Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (25, 'Opera');
INSERT INTO public.bookshelves (id, name) VALUES (26, 'Christmas');
INSERT INTO public.bookshelves (id, name) VALUES (27, 'Mathematics');
INSERT INTO public.bookshelves (id, name) VALUES (28, 'Fantasy');
INSERT INTO public.bookshelves (id, name) VALUES (29, 'Philosophy');
INSERT INTO public.bookshelves (id, name) VALUES (30, 'Historical Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (31, 'Bestsellers, American, 1895-1923');
INSERT INTO public.bookshelves (id, name) VALUES (32, 'Science Fiction by Women');
INSERT INTO public.bookshelves (id, name) VALUES (33, 'Arthurian Legends');
INSERT INTO public.bookshelves (id, name) VALUES (34, 'Contemporary Reviews');
INSERT INTO public.bookshelves (id, name) VALUES (35, 'Detective Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (36, 'School Stories');
INSERT INTO public.bookshelves (id, name) VALUES (37, 'Mystery Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (38, 'Art');
INSERT INTO public.bookshelves (id, name) VALUES (39, 'Photography');
INSERT INTO public.bookshelves (id, name) VALUES (40, 'Bibliomania');
INSERT INTO public.bookshelves (id, name) VALUES (41, 'Crime Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (42, 'Australia');
INSERT INTO public.bookshelves (id, name) VALUES (43, 'Animals-Domestic');
INSERT INTO public.bookshelves (id, name) VALUES (44, 'Paganism');
INSERT INTO public.bookshelves (id, name) VALUES (45, 'Classical Antiquity');
INSERT INTO public.bookshelves (id, name) VALUES (46, 'Scouts');
INSERT INTO public.bookshelves (id, name) VALUES (47, 'World War II');
INSERT INTO public.bookshelves (id, name) VALUES (48, 'Children''s Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (49, 'Humor');
INSERT INTO public.bookshelves (id, name) VALUES (50, 'Folklore');
INSERT INTO public.bookshelves (id, name) VALUES (51, 'World War I');
INSERT INTO public.bookshelves (id, name) VALUES (52, 'Anarchism');
INSERT INTO public.bookshelves (id, name) VALUES (53, 'United Kingdom');
INSERT INTO public.bookshelves (id, name) VALUES (54, 'Western');
INSERT INTO public.bookshelves (id, name) VALUES (55, 'Biographies');
INSERT INTO public.bookshelves (id, name) VALUES (56, 'Pirates, Buccaneers, Corsairs, etc.');
INSERT INTO public.bookshelves (id, name) VALUES (57, 'Crime Nonfiction');
INSERT INTO public.bookshelves (id, name) VALUES (58, 'Psychology');
INSERT INTO public.bookshelves (id, name) VALUES (59, 'Children''s Book Series');
INSERT INTO public.bookshelves (id, name) VALUES (60, 'Animals-Wild-Birds');
INSERT INTO public.bookshelves (id, name) VALUES (61, 'Children''s Picture Books');
INSERT INTO public.bookshelves (id, name) VALUES (62, 'DE Sachbuch');
INSERT INTO public.bookshelves (id, name) VALUES (63, 'Children''s Myths, Fairy Tales, etc.');
INSERT INTO public.bookshelves (id, name) VALUES (64, 'India');
INSERT INTO public.bookshelves (id, name) VALUES (65, 'Children''s History');
INSERT INTO public.bookshelves (id, name) VALUES (66, 'Medicine');
INSERT INTO public.bookshelves (id, name) VALUES (67, 'FR Littérature');
INSERT INTO public.bookshelves (id, name) VALUES (68, 'FR Nouvelles');
INSERT INTO public.bookshelves (id, name) VALUES (69, 'FR Science fiction');
INSERT INTO public.bookshelves (id, name) VALUES (70, 'Cookery');
INSERT INTO public.bookshelves (id, name) VALUES (71, 'Travel');
INSERT INTO public.bookshelves (id, name) VALUES (72, 'Napoleonic(Bookshelf)');
INSERT INTO public.bookshelves (id, name) VALUES (73, 'Children''s Verse');
INSERT INTO public.bookshelves (id, name) VALUES (74, 'Popular Science Monthly');
INSERT INTO public.bookshelves (id, name) VALUES (75, 'One Act Plays');
INSERT INTO public.bookshelves (id, name) VALUES (76, 'IT Poesia');
INSERT INTO public.bookshelves (id, name) VALUES (77, 'Italy');
INSERT INTO public.bookshelves (id, name) VALUES (78, 'Africa');
INSERT INTO public.bookshelves (id, name) VALUES (79, 'South Africa');
INSERT INTO public.bookshelves (id, name) VALUES (80, 'Zoology');
INSERT INTO public.bookshelves (id, name) VALUES (81, 'Science');
INSERT INTO public.bookshelves (id, name) VALUES (82, 'Botany');
INSERT INTO public.bookshelves (id, name) VALUES (83, 'Biology');
INSERT INTO public.bookshelves (id, name) VALUES (84, 'Physiology');
INSERT INTO public.bookshelves (id, name) VALUES (85, 'FR Théâtre');
INSERT INTO public.bookshelves (id, name) VALUES (86, 'Chemistry');
INSERT INTO public.bookshelves (id, name) VALUES (87, 'Anthropology');
INSERT INTO public.bookshelves (id, name) VALUES (88, 'Horticulture');
INSERT INTO public.bookshelves (id, name) VALUES (89, 'New Zealand');
INSERT INTO public.bookshelves (id, name) VALUES (90, 'Germany');
INSERT INTO public.bookshelves (id, name) VALUES (91, 'Mythology');
INSERT INTO public.bookshelves (id, name) VALUES (92, 'Judaism');
INSERT INTO public.bookshelves (id, name) VALUES (93, 'Short Stories');
INSERT INTO public.bookshelves (id, name) VALUES (94, 'British Law');
INSERT INTO public.bookshelves (id, name) VALUES (95, 'Animals-Wild');
INSERT INTO public.bookshelves (id, name) VALUES (96, 'Buddhism');
INSERT INTO public.bookshelves (id, name) VALUES (97, 'Egypt');
INSERT INTO public.bookshelves (id, name) VALUES (98, 'DE Drama');
INSERT INTO public.bookshelves (id, name) VALUES (99, 'Greece');
INSERT INTO public.bookshelves (id, name) VALUES (100, 'Suffrage');
INSERT INTO public.bookshelves (id, name) VALUES (101, 'Atheism');
INSERT INTO public.bookshelves (id, name) VALUES (102, 'DE Prosa');
INSERT INTO public.bookshelves (id, name) VALUES (103, 'DE Lyrik');
INSERT INTO public.bookshelves (id, name) VALUES (104, 'Children''s Instructional Books');
INSERT INTO public.bookshelves (id, name) VALUES (105, 'DE Kinderbuch');
INSERT INTO public.bookshelves (id, name) VALUES (106, 'Hinduism');
INSERT INTO public.bookshelves (id, name) VALUES (107, 'Islam');
INSERT INTO public.bookshelves (id, name) VALUES (108, 'Canada');
INSERT INTO public.bookshelves (id, name) VALUES (109, 'PT Contos');
INSERT INTO public.bookshelves (id, name) VALUES (110, 'Animals-Wild-Insects');
INSERT INTO public.bookshelves (id, name) VALUES (111, 'Microbiology');
INSERT INTO public.bookshelves (id, name) VALUES (112, 'Spanish American War');
INSERT INTO public.bookshelves (id, name) VALUES (113, 'Boer War');
INSERT INTO public.bookshelves (id, name) VALUES (114, 'Children''s Anthologies');
INSERT INTO public.bookshelves (id, name) VALUES (115, 'The Mirror of Literature, Amusement, and Instruction');
INSERT INTO public.bookshelves (id, name) VALUES (116, 'PT Poesia');
INSERT INTO public.bookshelves (id, name) VALUES (117, 'Project Gutenberg');
INSERT INTO public.bookshelves (id, name) VALUES (118, 'France');
INSERT INTO public.bookshelves (id, name) VALUES (119, 'South America');
INSERT INTO public.bookshelves (id, name) VALUES (120, 'FR Biographie, Mémoires, Journal intime, Correspondance');
INSERT INTO public.bookshelves (id, name) VALUES (121, 'Music');
INSERT INTO public.bookshelves (id, name) VALUES (122, 'Erotic Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (123, 'Geology');
INSERT INTO public.bookshelves (id, name) VALUES (124, 'Astronomy');
INSERT INTO public.bookshelves (id, name) VALUES (125, 'Archaeology');
INSERT INTO public.bookshelves (id, name) VALUES (126, 'FR Poésie');
INSERT INTO public.bookshelves (id, name) VALUES (127, 'Technology');
INSERT INTO public.bookshelves (id, name) VALUES (128, 'Manufacturing');
INSERT INTO public.bookshelves (id, name) VALUES (129, 'Physics');
INSERT INTO public.bookshelves (id, name) VALUES (130, 'FR Langues');
INSERT INTO public.bookshelves (id, name) VALUES (131, 'Noteworthy Trials(Bookshelf)');
INSERT INTO public.bookshelves (id, name) VALUES (132, 'FR Philosophie, Religion et Morale');
INSERT INTO public.bookshelves (id, name) VALUES (133, 'Language Education');
INSERT INTO public.bookshelves (id, name) VALUES (134, 'Animal');
INSERT INTO public.bookshelves (id, name) VALUES (135, 'Children''s Biography');
INSERT INTO public.bookshelves (id, name) VALUES (136, 'Natural History');
INSERT INTO public.bookshelves (id, name) VALUES (137, 'German Language Books');
INSERT INTO public.bookshelves (id, name) VALUES (138, 'Racism');
INSERT INTO public.bookshelves (id, name) VALUES (139, 'FR Histoire');
INSERT INTO public.bookshelves (id, name) VALUES (140, 'Sociology');
INSERT INTO public.bookshelves (id, name) VALUES (141, 'IT Storia');
INSERT INTO public.bookshelves (id, name) VALUES (142, 'FR Sciences et Techniques');
INSERT INTO public.bookshelves (id, name) VALUES (143, 'Children''s Religion');
INSERT INTO public.bookshelves (id, name) VALUES (144, 'Women''s Travel Journals');
INSERT INTO public.bookshelves (id, name) VALUES (145, 'IT Romanzi storici');
INSERT INTO public.bookshelves (id, name) VALUES (146, 'IT Romanzi');
INSERT INTO public.bookshelves (id, name) VALUES (147, 'Argentina');
INSERT INTO public.bookshelves (id, name) VALUES (148, 'IT Racconti');
INSERT INTO public.bookshelves (id, name) VALUES (149, 'IT Scienza');
INSERT INTO public.bookshelves (id, name) VALUES (150, 'Masterpieces in Colour');
INSERT INTO public.bookshelves (id, name) VALUES (151, 'Esperanto');
INSERT INTO public.bookshelves (id, name) VALUES (152, 'IT Biografie');
INSERT INTO public.bookshelves (id, name) VALUES (153, 'FR Peuples et Sociétés');
INSERT INTO public.bookshelves (id, name) VALUES (154, 'Scientific American');
INSERT INTO public.bookshelves (id, name) VALUES (155, 'The Atlantic Monthly');
INSERT INTO public.bookshelves (id, name) VALUES (156, 'FR Humour');
INSERT INTO public.bookshelves (id, name) VALUES (157, 'Notes and Queries');
INSERT INTO public.bookshelves (id, name) VALUES (158, 'Punch');
INSERT INTO public.bookshelves (id, name) VALUES (159, 'FR Voyages et pays');
INSERT INTO public.bookshelves (id, name) VALUES (160, 'Witchcraft');
INSERT INTO public.bookshelves (id, name) VALUES (161, 'Crafts');
INSERT INTO public.bookshelves (id, name) VALUES (162, 'Education');
INSERT INTO public.bookshelves (id, name) VALUES (163, 'The Bay State Monthly');
INSERT INTO public.bookshelves (id, name) VALUES (164, 'FR Education et Enseignement');
INSERT INTO public.bookshelves (id, name) VALUES (165, 'Punchinello');
INSERT INTO public.bookshelves (id, name) VALUES (166, 'Czech');
INSERT INTO public.bookshelves (id, name) VALUES (167, 'FR Jeunesse');
INSERT INTO public.bookshelves (id, name) VALUES (168, 'Blackwood''s Edinburgh Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (169, 'The Strand Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (170, 'FR Littérature francophone');
INSERT INTO public.bookshelves (id, name) VALUES (171, 'IT Musica');
INSERT INTO public.bookshelves (id, name) VALUES (172, 'FR Chansons');
INSERT INTO public.bookshelves (id, name) VALUES (173, 'Architecture');
INSERT INTO public.bookshelves (id, name) VALUES (174, 'FR Occultisme');
INSERT INTO public.bookshelves (id, name) VALUES (175, 'FR Politique');
INSERT INTO public.bookshelves (id, name) VALUES (176, 'Transportation');
INSERT INTO public.bookshelves (id, name) VALUES (177, 'Animals-Wild-Mammals');
INSERT INTO public.bookshelves (id, name) VALUES (178, 'FR La Première Guerre Mondiale, 1914-1918');
INSERT INTO public.bookshelves (id, name) VALUES (179, 'FR Presse');
INSERT INTO public.bookshelves (id, name) VALUES (180, 'Famous Scots Series');
INSERT INTO public.bookshelves (id, name) VALUES (181, 'FR Guerres');
INSERT INTO public.bookshelves (id, name) VALUES (182, 'De Aarde en haar Volken');
INSERT INTO public.bookshelves (id, name) VALUES (183, 'McClure''s Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (184, 'English Civil War');
INSERT INTO public.bookshelves (id, name) VALUES (185, 'Forestry');
INSERT INTO public.bookshelves (id, name) VALUES (186, 'Bulgaria');
INSERT INTO public.bookshelves (id, name) VALUES (187, 'The American Missionary');
INSERT INTO public.bookshelves (id, name) VALUES (188, 'FR Contes');
INSERT INTO public.bookshelves (id, name) VALUES (189, 'FR Sports et loisirs');
INSERT INTO public.bookshelves (id, name) VALUES (190, 'Engineering');
INSERT INTO public.bookshelves (id, name) VALUES (191, 'Woodwork');
INSERT INTO public.bookshelves (id, name) VALUES (192, 'FR Femmes');
INSERT INTO public.bookshelves (id, name) VALUES (193, 'PT Política e Sociedade');
INSERT INTO public.bookshelves (id, name) VALUES (194, 'Lippincott''s Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (195, 'The International Magazine of Literature, Art, and Science');
INSERT INTO public.bookshelves (id, name) VALUES (196, 'Ecology');
INSERT INTO public.bookshelves (id, name) VALUES (197, 'Animals-Wild-Trapping');
INSERT INTO public.bookshelves (id, name) VALUES (198, 'The Brochure Series of Architectural Illustration');
INSERT INTO public.bookshelves (id, name) VALUES (199, 'Continental Monthly');
INSERT INTO public.bookshelves (id, name) VALUES (200, 'Current History');
INSERT INTO public.bookshelves (id, name) VALUES (201, 'The Journal of Negro History');
INSERT INTO public.bookshelves (id, name) VALUES (202, 'The National Preacher');
INSERT INTO public.bookshelves (id, name) VALUES (203, 'Chambers''s Edinburgh Journal');
INSERT INTO public.bookshelves (id, name) VALUES (204, 'Canon Law');
INSERT INTO public.bookshelves (id, name) VALUES (205, 'Dew Drops');
INSERT INTO public.bookshelves (id, name) VALUES (206, 'The Nursery');
INSERT INTO public.bookshelves (id, name) VALUES (207, 'Love');
INSERT INTO public.bookshelves (id, name) VALUES (208, 'L''Illustration');
INSERT INTO public.bookshelves (id, name) VALUES (209, 'Early English Text Society');
INSERT INTO public.bookshelves (id, name) VALUES (210, 'FR Séduction et libertinage');
INSERT INTO public.bookshelves (id, name) VALUES (211, 'PT Língua Portuguesa');
INSERT INTO public.bookshelves (id, name) VALUES (212, 'Godey''s Lady''s Book');
INSERT INTO public.bookshelves (id, name) VALUES (213, 'The Aldine');
INSERT INTO public.bookshelves (id, name) VALUES (214, 'IT Botanica');
INSERT INTO public.bookshelves (id, name) VALUES (215, 'Bulletin de Lille');
INSERT INTO public.bookshelves (id, name) VALUES (216, 'The American Architect and Building News');
INSERT INTO public.bookshelves (id, name) VALUES (217, 'The Great Round World And What Is Going On In It');
INSERT INTO public.bookshelves (id, name) VALUES (218, 'St. Nicholas Magazine for Boys and Girls');
INSERT INTO public.bookshelves (id, name) VALUES (219, 'Microscopy');
INSERT INTO public.bookshelves (id, name) VALUES (220, 'PT Ciência e Técnica');
INSERT INTO public.bookshelves (id, name) VALUES (221, 'PT História');
INSERT INTO public.bookshelves (id, name) VALUES (222, 'PT Biografia');
INSERT INTO public.bookshelves (id, name) VALUES (223, 'Camping');
INSERT INTO public.bookshelves (id, name) VALUES (224, 'The Unpopular Review');
INSERT INTO public.bookshelves (id, name) VALUES (225, 'PT Romance');
INSERT INTO public.bookshelves (id, name) VALUES (226, 'PT Infantil e Juvenil');
INSERT INTO public.bookshelves (id, name) VALUES (227, 'IT Salute');
INSERT INTO public.bookshelves (id, name) VALUES (228, 'Bahá''í Faith');
INSERT INTO public.bookshelves (id, name) VALUES (229, 'Golden Days for Boys and Girls');
INSERT INTO public.bookshelves (id, name) VALUES (230, 'FR Peinture');
INSERT INTO public.bookshelves (id, name) VALUES (231, 'IT Religione e Spiritualità');
INSERT INTO public.bookshelves (id, name) VALUES (232, 'The Argosy');
INSERT INTO public.bookshelves (id, name) VALUES (233, 'The Botanical Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (234, 'FR Musique');
INSERT INTO public.bookshelves (id, name) VALUES (235, 'IT Teatro in versi');
INSERT INTO public.bookshelves (id, name) VALUES (236, 'FR Villes');
INSERT INTO public.bookshelves (id, name) VALUES (237, 'Prairie Farmer');
INSERT INTO public.bookshelves (id, name) VALUES (238, 'PT Teatro');
INSERT INTO public.bookshelves (id, name) VALUES (239, 'FR Illustrateurs');
INSERT INTO public.bookshelves (id, name) VALUES (240, 'Mrs Whittelsey''s Magazine for Mothers and Daughters');
INSERT INTO public.bookshelves (id, name) VALUES (241, 'IT Letteratura per ragazzi');
INSERT INTO public.bookshelves (id, name) VALUES (242, 'IT Viaggi');
INSERT INTO public.bookshelves (id, name) VALUES (243, 'IT Teatro in prosa');
INSERT INTO public.bookshelves (id, name) VALUES (244, 'IT Umorismo');
INSERT INTO public.bookshelves (id, name) VALUES (245, 'FR Services publics');
INSERT INTO public.bookshelves (id, name) VALUES (246, 'The Philatelic Digital Library Project');
INSERT INTO public.bookshelves (id, name) VALUES (247, 'The Girls Own Paper');
INSERT INTO public.bookshelves (id, name) VALUES (248, 'Northern Nut Growers Association');
INSERT INTO public.bookshelves (id, name) VALUES (249, 'The Illustrated War News');
INSERT INTO public.bookshelves (id, name) VALUES (250, 'Mycology');
INSERT INTO public.bookshelves (id, name) VALUES (251, 'FR Métiers et Artisanat');
INSERT INTO public.bookshelves (id, name) VALUES (252, 'The Arena');
INSERT INTO public.bookshelves (id, name) VALUES (253, 'The Knickerbocker');
INSERT INTO public.bookshelves (id, name) VALUES (254, 'IT Legge');
INSERT INTO public.bookshelves (id, name) VALUES (255, 'IT Scienze politiche');
INSERT INTO public.bookshelves (id, name) VALUES (256, 'IT Psicologia e Sociologia');
INSERT INTO public.bookshelves (id, name) VALUES (257, 'PT Navegações e Explorações');
INSERT INTO public.bookshelves (id, name) VALUES (258, 'IT Letteratura');
INSERT INTO public.bookshelves (id, name) VALUES (259, 'The American Journal of Archaeology');
INSERT INTO public.bookshelves (id, name) VALUES (260, 'Astounding Stories');
INSERT INTO public.bookshelves (id, name) VALUES (261, 'Donahoe''s Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (262, 'The Idler');
INSERT INTO public.bookshelves (id, name) VALUES (263, 'The Menorah Journal');
INSERT INTO public.bookshelves (id, name) VALUES (264, 'Buchanan''s Journal of Man');
INSERT INTO public.bookshelves (id, name) VALUES (265, 'The Mirror of Taste, and Dramatic Censor');
INSERT INTO public.bookshelves (id, name) VALUES (266, 'IT Economia');
INSERT INTO public.bookshelves (id, name) VALUES (267, 'PT Arte');
INSERT INTO public.bookshelves (id, name) VALUES (268, 'FR Droit et Justice');
INSERT INTO public.bookshelves (id, name) VALUES (269, 'PT Periódicos');
INSERT INTO public.bookshelves (id, name) VALUES (270, 'IT Linguistica');
INSERT INTO public.bookshelves (id, name) VALUES (271, 'Mediæval Town Series');
INSERT INTO public.bookshelves (id, name) VALUES (272, 'Norway');
INSERT INTO public.bookshelves (id, name) VALUES (273, 'The Stars and Stripes');
INSERT INTO public.bookshelves (id, name) VALUES (274, 'Harper''s New Monthly Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (275, 'Little Folks');
INSERT INTO public.bookshelves (id, name) VALUES (276, 'Birds, Illustrated by Color Photography');
INSERT INTO public.bookshelves (id, name) VALUES (277, 'Celtic Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (278, 'Armour''s Monthly Cook Book');
INSERT INTO public.bookshelves (id, name) VALUES (279, 'The Writer');
INSERT INTO public.bookshelves (id, name) VALUES (280, 'The Christian Foundation');
INSERT INTO public.bookshelves (id, name) VALUES (281, 'Mother Earth');
INSERT INTO public.bookshelves (id, name) VALUES (282, 'IT Numismatica');
INSERT INTO public.bookshelves (id, name) VALUES (283, 'FR Livres, Collections et Bibliophilie');
INSERT INTO public.bookshelves (id, name) VALUES (284, 'Barnavännen');
INSERT INTO public.bookshelves (id, name) VALUES (285, 'The Mentor');
INSERT INTO public.bookshelves (id, name) VALUES (286, 'IT Arte varia');
INSERT INTO public.bookshelves (id, name) VALUES (287, 'IT Geografia');
INSERT INTO public.bookshelves (id, name) VALUES (288, 'The Economist');
INSERT INTO public.bookshelves (id, name) VALUES (289, 'Ainslee''s');
INSERT INTO public.bookshelves (id, name) VALUES (290, 'The American Quarterly Review');
INSERT INTO public.bookshelves (id, name) VALUES (291, 'Harper''s Young People');
INSERT INTO public.bookshelves (id, name) VALUES (292, 'The Speaker');
INSERT INTO public.bookshelves (id, name) VALUES (293, 'Illustrators');
INSERT INTO public.bookshelves (id, name) VALUES (294, 'The Esperantist');
INSERT INTO public.bookshelves (id, name) VALUES (295, 'Graham''s Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (296, 'The North American Medical and Surgical Journal');
INSERT INTO public.bookshelves (id, name) VALUES (297, 'Our Young Folks');
INSERT INTO public.bookshelves (id, name) VALUES (298, 'The Mayflower');
INSERT INTO public.bookshelves (id, name) VALUES (299, 'The Contemporary Review');
INSERT INTO public.bookshelves (id, name) VALUES (300, 'Animals-Wild-Reptiles and Amphibians');
INSERT INTO public.bookshelves (id, name) VALUES (301, 'The Galaxy');
INSERT INTO public.bookshelves (id, name) VALUES (302, 'The Baptist Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (303, 'The Church of England Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (304, 'IT Teatro dialettale');
INSERT INTO public.bookshelves (id, name) VALUES (305, 'The Irish Ecclesiastical Record');
INSERT INTO public.bookshelves (id, name) VALUES (306, 'The Scrap Book');
INSERT INTO public.bookshelves (id, name) VALUES (307, 'Garden and Forest');
INSERT INTO public.bookshelves (id, name) VALUES (308, 'IT Filosofia');
INSERT INTO public.bookshelves (id, name) VALUES (309, 'IT Cucina');
INSERT INTO public.bookshelves (id, name) VALUES (310, 'Journal of Entomology and Zoology');
INSERT INTO public.bookshelves (id, name) VALUES (311, 'Child''s Own Book of Great Musicians');
INSERT INTO public.bookshelves (id, name) VALUES (312, 'IT Folklore');
INSERT INTO public.bookshelves (id, name) VALUES (313, 'IT Discorsi e Orazioni');
INSERT INTO public.bookshelves (id, name) VALUES (314, 'FR Prix Nobel');
INSERT INTO public.bookshelves (id, name) VALUES (315, 'The Irish Penny Journal');
INSERT INTO public.bookshelves (id, name) VALUES (316, 'FR Chroniques');
INSERT INTO public.bookshelves (id, name) VALUES (317, 'The Catholic World');
INSERT INTO public.bookshelves (id, name) VALUES (318, 'Bird-Lore');
INSERT INTO public.bookshelves (id, name) VALUES (319, 'Scribner''s Magazine');
INSERT INTO public.bookshelves (id, name) VALUES (320, 'The Yellow Book');
INSERT INTO public.bookshelves (id, name) VALUES (321, 'IT Narrativa varia');
INSERT INTO public.bookshelves (id, name) VALUES (322, 'FR Beaux-Arts');
INSERT INTO public.bookshelves (id, name) VALUES (323, 'Poetry, A Magazine of Verse');
INSERT INTO public.bookshelves (id, name) VALUES (324, 'IT Tecnologia');
INSERT INTO public.bookshelves (id, name) VALUES (325, 'Romantic Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (326, 'IT Scienze militari');
INSERT INTO public.bookshelves (id, name) VALUES (327, 'IT Miscellanea');
INSERT INTO public.bookshelves (id, name) VALUES (328, 'IT Architettura');
INSERT INTO public.bookshelves (id, name) VALUES (329, 'IT Archeologia e Storia dell''arte');
INSERT INTO public.bookshelves (id, name) VALUES (330, 'General Fiction');
INSERT INTO public.bookshelves (id, name) VALUES (331, 'The Haslemere Museum Gazette');
INSERT INTO public.bookshelves (id, name) VALUES (332, 'FR Nouveautés');
INSERT INTO public.bookshelves (id, name) VALUES (333, 'London Medical Gazette');
INSERT INTO public.bookshelves (id, name) VALUES (334, 'Maps and Cartography');
INSERT INTO public.bookshelves (id, name) VALUES (335, 'IT Agraria');
